<?php
/*
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/** @var OpenNode_Bitcoin_Block_Info $block */
$block = $this;

/** @var OpenNode_Bitcoin_Helper_Data $helper */
$helper = Mage::helper('opennode_bitcoin');
$charge = null;

try {
    $charge = $block->getCharge();
} catch (Exception $e) {
    Mage::logException($e);
} ?>

<?php if (is_null($charge)) : ?>
    <span><?php print $helper->__('It\'s not possible to obtain the transaction details at this moment.'); ?></span>
    <?php return; ?>
<?php endif; ?>

<table class="payment-info" style="width: 100%; table-layout: fixed;">
    <tbody>
    <tr>
        <td style="width: 150px;"><?php print $helper->__('Charge ID'); ?></td>
        <td><?php print $block->escapeHtml($charge->id); ?></td>
    </tr>
    <tr>
        <td><?php print $helper->__('Amount (Satoshis)'); ?></td>
        <td><?php print $block->escapeHtml($charge->amount); ?></td>
    </tr>
    <tr>
        <td><?php print $helper->__('Status'); ?></td>
        <td><?php print $block->escapeHtml($charge->status); ?></td>
    </tr>
    <tr>
        <td><?php print $helper->__('Auto-Settle'); ?></td>
        <td><?php print $block->escapeHtml($charge->auto_settle ? $helper->__('Yes') : $helper->__('No')); ?></td>
    </tr>
    </tbody>

    <?php if (!is_null($charge->lightning_invoice)) : ?>
        <tbody>
        <tr>
            <td colspan="2" style="padding-top: 10px; font-weight: bold; border-bottom: 1px solid #d6d6d6;">
                <?php print $helper->__('Lightning Invoice'); ?>
            </td>
        </tr>
        <tr>
            <td><?php print $helper->__('Request Hash'); ?></td>
            <td style="word-break: break-all;width:100px;">
                <?php print $block->escapeHtml($charge->lightning_invoice['payreq']); ?>
            </td>
        </tr>
        <tr>
            <td><?php print $helper->__('Created At'); ?></td>
            <td><?php print $block->escapeHtml($block->getStoreDate($charge->lightning_invoice['created_at'])); ?></td>
        </tr>
        <tr>
            <td><?php print $helper->__('Expires At'); ?></td>
            <td><?php print $block->escapeHtml($block->getStoreDate($charge->lightning_invoice['expires_at'])); ?></td>
        </tr>
        <tr>
            <td><?php print $helper->__('Settled At'); ?></td>
            <td>
                <?php if (isset($charge->lightning_invoice['settled_at'])) : ?>
                    <?php print $block->escapeHtml($block->getStoreDate($charge->lightning_invoice['settled_at'])); ?>
                <?php else: ?>
                    <?php print $helper->__('Not settled yet'); ?>
                <?php endif; ?>
            </td>
        </tr>
        </tbody>
    <?php endif; ?>

    <?php if (!is_null($charge->chain_invoice)) : ?>
        <?php $addressUrl = $helper->getAddressExplorerUrl($charge->chain_invoice['address']); ?>
        <?php $txUrl = $helper->getTransactionExplorerUrl($charge->chain_invoice['tx']); ?>

        <tbody>
        <tr>
            <td colspan="2" style="padding-top: 10px; font-weight: bold; border-bottom: 1px solid #d6d6d6;">
                <?php print $helper->__('Chain Invoice'); ?>
            </td>
        </tr>
        <tr>
            <td><?php print $helper->__('Address'); ?></td>
            <td>
                <a target="_blank" rel="noopener noreferrer" href="<?php print $block->escapeHtml($addressUrl); ?>">
                    <?php print $block->escapeHtml($charge->chain_invoice['address']); ?>
                </a>
            </td>
        </tr>
        <tr>
            <td><?php print $helper->__('Transaction ID'); ?></td>
            <td>
                <?php if (isset($charge->chain_invoice['tx'])) : ?>
                    <a target="_blank" rel="noopener noreferrer" href="<?php print $block->escapeHtml($txUrl); ?>">
                        <?php print $block->escapeHtml($charge->chain_invoice['tx']); ?>
                    </a>
                <?php else: ?>
                    <?php print $helper->__('No transaction seen on the blockchain yet'); ?>
                <?php endif; ?>
            </td>
        </tr>
        <tr>
            <td><?php print $helper->__('Settled At'); ?></td>
            <td>
                <?php if (isset($charge->chain_invoice['settled_at'])) : ?>
                    <?php print $block->escapeHtml($block->getStoreDate($charge->chain_invoice['settled_at'])); ?>
                <?php else: ?>
                    <?php print $helper->__('Not settled yet'); ?>
                <?php endif; ?>
            </td>
        </tr>
        </tbody>
    <?php endif; ?>
</table>