<?php
/*
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/** @var OpenNode_Bitcoin_Block_Info $block */
$block = $this;

/** @var OpenNode_Bitcoin_Helper_Data $helper */
$helper = Mage::helper('opennode_bitcoin');
$charge = $block->getCharge(); ?>

<?php if (is_null($charge)) : ?>
    <span><?php print $helper->__('It\'s not possible to obtain the transaction details at this moment.'); ?></span>
    <?php return; ?>
<?php endif; ?>

<?php if($block->getPaymentEnvironment() == OpenNode_Bitcoin_Model_Bitcoin::OPENNODE_ENV_DEV) : ?>
    <div id="messages">
        <ul class="messages">
            <li class="error-msg">
                <ul>
                    <li><span><?php print $helper->__('Payment created using the TESTNET!'); ?></span></li>
                </ul>
            </li>
        </ul>
    </div>
<?php endif; ?>

<table class="payment-info" style="width: 100%; table-layout: fixed;">
    <tbody>
    <tr>
        <td style="width: 150px;"><?php print $helper->__('Charge ID'); ?></td>
        <td><?php print $block->escapeHtml($charge->getTransactionId()); ?></td>
    </tr>
    <tr>
        <td><?php print $helper->__('Amount (Satoshis ~ BTC)'); ?></td>
        <td><?php print $block->escapeHtml($charge->getAmount()); ?> ~ <?php print $block->escapeHtml($charge->getAmountBtc()) ?></td>
    </tr>
    <tr>
        <td><?php print $helper->__('Status'); ?></td>
        <td><?php print $block->escapeHtml($charge->getStatusLabel()); ?></td>
    </tr>
    <tr>
        <td><?php print $helper->__('Auto-Settle'); ?></td>
        <td><?php print $block->escapeHtml($charge->getAutoSettle() ? $helper->__('Yes') : $helper->__('No')); ?></td>
    </tr>
    <tr>
      <td><?php print $helper->__('Transactions'); ?></td>
      <td><?php print $block->escapeHtml($charge->getTransactions()->count()); ?></td>
    </tr>
    </tbody>

    <?php if ($charge->getLightningInvoice()->hasData()) : ?>
        <tbody>
        <tr>
            <td colspan="2" style="padding-top: 10px; font-weight: bold; border-bottom: 1px solid #d6d6d6;">
                <?php print $helper->__('Lightning Invoice'); ?>
            </td>
        </tr>
        <tr>
            <td><?php print $helper->__('Request Hash'); ?></td>
            <td style="word-break: break-all;width:100px;">
                <?php print $block->escapeHtml($charge->getLightningInvoice()->getAddress()); ?>
            </td>
        </tr>
        <tr>
            <td><?php print $helper->__('Created At'); ?></td>
            <td><?php print $block->escapeHtml($block->getStoreDate($charge->getLightningInvoice()->getCreatedAt())); ?></td>
        </tr>
        <tr>
            <td><?php print $helper->__('Expires At'); ?></td>
            <td><?php print $block->escapeHtml($block->getStoreDate($charge->getLightningInvoice()->getExpiresAt())); ?></td>
        </tr>
        <tr>
            <td><?php print $helper->__('Settled At'); ?></td>
            <td>
                <?php if (!is_null($charge->getLightningInvoice()->getSettledAt())) : ?>
                    <?php print $block->escapeHtml($block->getStoreDate($charge->getLightningInvoice()->getSettledAt())); ?>
                <?php else: ?>
                    <?php print $helper->__('Not settled yet'); ?>
                <?php endif; ?>
            </td>
        </tr>
        </tbody>
    <?php endif; ?>

    <?php if ($charge->getChainInvoice()->hasData()) : ?>
        <?php $addressUrl = $helper->getAddressExplorerUrl($charge->getChainInvoice()->getAddress()); ?>
        <?php $txUrl = $helper->getTransactionExplorerUrl($charge->getChainInvoice()->getTx()); ?>

        <tbody>
        <tr>
            <td colspan="2" style="padding-top: 10px; font-weight: bold; border-bottom: 1px solid #d6d6d6;">

                <?php print $helper->__('Chain Invoice'); ?>
            </td>
        </tr>
        <tr>
            <td><?php print $helper->__('Address'); ?></td>
            <td>
                <a target="_blank" rel="noopener noreferrer" href="<?php print $block->escapeHtml($addressUrl); ?>">
                    <?php print $block->escapeHtml($charge->getChainInvoice()->getAddress()); ?>
                </a>
            </td>
        </tr>
        <tr>
            <td><?php print $helper->__('Transaction ID'); ?></td>
            <td>
                <?php if (!is_null($charge->getChainInvoice()->getTx())) : ?>
                    <a target="_blank" rel="noopener noreferrer" href="<?php print $block->escapeHtml($txUrl); ?>">
                        <?php print $block->escapeHtml($charge->getChainInvoice()->getTx()); ?>
                    </a>
                <?php else: ?>
                    <?php print $helper->__('No transaction seen on the blockchain yet'); ?>
                <?php endif; ?>
            </td>
        </tr>
        <tr>
            <td><?php print $helper->__('Settled At'); ?></td>
            <td>
                <?php if (!is_null($charge->getChainInvoice()->getSettledAt())) : ?>
                    <?php print $block->escapeHtml($block->getStoreDate($charge->getChainInvoice()->getSettledAt())); ?>
                <?php else: ?>
                    <?php print $helper->__('Not settled yet'); ?>
                <?php endif; ?>
            </td>
        </tr>
        </tbody>
    <?php endif; ?>

    <?php if ($charge->getTransactions()->count() > 1) : ?>
        <tbody>
            <?php /** @var OpenNode_Bitcoin_Model_Transaction $transaction */ ?>
            <?php foreach ($charge->getTransactions() as $index => $transaction) : ?>
            <tr>
                <td colspan="2" style="padding-top: 10px; font-weight: bold; border-bottom: 1px solid #d6d6d6;">
                    <?php print $helper->__('Transaction #%d', $index + 1); ?>
                </td>
            </tr>
            <tr>
                <td><?php print $helper->__('Address'); ?></td>
                <td>
                    <a target="_blank" rel="noopener noreferrer" href="<?php print $block->escapeHtml($addressUrl); ?>">
                        <?php print $block->escapeHtml($transaction->getAddress()); ?>
                    </a>
                </td>
            </tr>
            <tr>
                <td><?php print $helper->__('Transaction ID'); ?></td>
                <td>
                    <a target="_blank" rel="noopener noreferrer" href="<?php print $block->escapeHtml($txUrl); ?>">
                        <?php print $block->escapeHtml($transaction->getTx()); ?>
                    </a>
                </td>
            </tr>
            <tr>
                <td><?php print $helper->__('Settled At'); ?></td>
                <td>
                    <?php if (!is_null($transaction->getSettledAt())) : ?>
                        <?php print $block->escapeHtml($block->getStoreDate($transaction->getSettledAt())); ?>
                    <?php else: ?>
                        <?php print $helper->__('Not settled yet'); ?>
                    <?php endif; ?>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
        <?php endif; ?>
</table>