<?php
/*
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/** @var $block OpenNode_Bitcoin_Block_Payment */
$block = $this;

/** @var $h OpenNode_Bitcoin_Helper_Data */
$h = Mage::helper('opennode_bitcoin');

$charge = $block->getCharge(); ?>


<div class="block-opennode">

    <div class="block block-summary">
        <div class="block-title">
            <span><strong><span><?php print $h->__('Order Summary'); ?></span></strong></span>
        </div>

        <div><?php print $block->escapeHtml($charge->description); ?></div>

        <div>
            <div>
                <?php print $h->__('%s Satoshis ~ %s BTC', $charge->amount, $h->satoshiToBtc($charge->amount)); ?>
            </div>
            <div><?php print $h->__('%s %s', $charge->source_fiat_value, $charge->currency); ?></div>
        </div>
    </div>

    <div class="col2-set block-payment-methods">
        <div class="block-title">
            <span><strong><span><?php print $h->__('Select bitcoin payment method'); ?></span></strong></span>
        </div>

        <div class="col-1">
            <div class="box payment-method">
                <div class="box-title">
                    <strong><?php print $h->__('Lightning Network'); ?></strong>
                </div>
                <div class="box-content">
                    <div class="fee"><?php print $h->__('network fee of %s %s', '0.00', 'USD'); ?></div>
                    <div class="qr-code" data-ecl="M"
                         data-address="<?php print $block->escapeHtml($charge->lightning_invoice['payreq']); ?>"></div>
                    <div>
                        <a class="button"
                           href="lightning:<?php print $block->escapeHtml($charge->lightning_invoice['payreq']); ?>"><?php print $h->__('Open in wallet'); ?></a>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-2">
            <div class="box payment-method">
                <div class="box-title">
                    <strong><?php print $h->__('On-Chain'); ?></strong>
                </div>
                <div class="box-content">
                    <div class="fee"><?php print $h->__('network fee of %s %s', '0.00', 'USD'); ?></div>
                    <div class="qr-code" data-ecl="M"
                         data-address="<?php print $block->escapeHtml($charge->chain_invoice['address']); ?>"></div>
                    <div>
                        <a target="_blank" class="button"
                           href="lightning:<?php print $block->escapeHtml($charge->chain_invoice['address']); ?>"><?php print $h->__('Open in wallet'); ?></a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col2-set block-actions">
        <div class="col-1"><!-- Just some filler so we can achieve two columns with the default Magento theme! --></div>
        <div class="col-2">
            <div class="box action action-pay">
                <div class="box-content">
                    <form action="<?php print Mage::getUrl('opennode_bitcoin/payment/success'); ?>" method="get">
                        <ul id="payment-status-unpaid" class="form-list">
                            <li style="margin-bottom: 20px;"><?php print $h->__('Your payment has not been seen in the mempool (if using on-chain payment) or settled in the Ligthning Network. If still decide to continue your order will be placed in a <i>Pending Payment</i> status and will be cancelled in 1 hour.'); ?></li>


                            <li class="a-right">
                                <label for="confirm"><?php print $h->__('I understand. I will continue now instead of waiting for confirmation.'); ?></label>
                                <input style="vertical-align: middle;" id="confirm" required class="checkbox" type="checkbox">
                            </li>

                            <li class="a-right">
                                <button class="button" type="submit"><?php print $h->__('I\'ll pay later'); ?></button>
                            </li>
                        </ul>

                        <ul id="payment-status-paid" class="form-list" style="display: none;">
                            <li>
                                <p><?php print $h->__('Your order was paid successfully.'); ?></p>
                                <p><?php print $h->__('Your should be redirected to the order summary automatically in a few moments.'); ?></p>
                            </li>

                            <li class="a-right">
                                <button class="button" type="submit"><?php print $h->__('Continue to order summary'); ?></button>
                            </li>
                        </ul>

                        <?php echo $this->getBlockHtml('formkey') ?>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="info-set col2-set">
        <div class="col-1">
            <div class="box action-cancel">
                <div class="box-content">
                    <a href="<?php print $block->escapeHtml($block->getCancelUrl()); ?>">
                        <?php print $h->__('Cancel the order and return to %s', $block->getStoreName()); ?>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>



<!--
<div><?php var_dump($block->getParams()); ?></div>
<div><?php var_dump($charge); ?></div>
-->

<script src="https://cdn.jsdelivr.net/npm/qrcode-svg@1.0.0/dist/qrcode.min.js"></script>
<script>
    document.observe("dom:loaded", function () {
        $$('div[data-address]').forEach(item => {
            if (!item.dataset.address || item.dataset.address.length === 0) {
                item.innerHTML = '<?php print $block->__('Something wrong'); ?>';
                return;
            }

            item.innerHTML = new QRCode({
                content: item.dataset.address,
                padding: 4,
                width: 200,
                height: 200,
                color: '#000000',
                background: '#ffffff',
                ecl: item.dataset.ecl
            }).svg();
        });

        setInterval(function () {
            new Ajax.Request('<?php print $block->escapeHtml($block->getStatusUrl()); ?>', {
                onSuccess: function (response) {

                    console.log(response);

                    if (response.responseJSON.status === 'paid') {
                        $('payment-status-unpaid').style.display = 'none';
                        $('payment-status-paid').style.display = 'block';
                    }

                },
                onFailure: function (response) {
                    console.log(response);
                }
            });
        }, 1000);
    });
</script>

<style>
    /*.block-opennode .payment-methods {*/
    /*white-space: nowrap;*/
    /*}*/

    .block-opennode .payment-method {
        text-align: center;
        /*display: inline-block;*/
        padding: 20px 0;
        /*white-space: normal;*/
        /*width: 50%;*/
        background-color: #f4f4f4;
        border: 1px solid #cccccc;
    }

    .block-opennode .block-actions .action-pay {
        background-color: #f4f4f4;
        border: 1px solid #cccccc;
        padding: 20px;
        /*width: 50%;*/
    }

    .block-opennode .payment-method .qr-code {
        margin: 10px 0;
    }

    .block-opennode .payment-method .fee {
        font-size: 14px;
    }

    .block-opennode .block-actions {
        clear: both;
    }

    .block-opennode .action-cancel {
        font-size: 11.4px;
    }

    .block-opennode .block-actions .action-pay {
        /*margin-bottom: 30px;*/
    }
</style>