<?php
/*
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/** @var $block OpenNode_Bitcoin_Block_Payment */
$block = $this;

/** @var $h OpenNode_Bitcoin_Helper_Data */
$h = Mage::helper('opennode_bitcoin');

$charge = $block->getCharge(); ?>


<div class="block block-opennode">
    <div class="block-title">
        <span><strong><span><?php print $h->__('Order Summary'); ?></span></strong></span>
    </div>

    <div class="description h-space"><?php print $block->escapeHtml($charge->description); ?></div>

    <div class="total h-space">
        <div class="text-main-dark">
            <?php print $h->__('%s Satoshis ~ %s BTC', $charge->amount, $h->satoshiToBtc($charge->amount)); ?>
        </div>
        <div class="text-grey-darkest"><?php print $h->__('%s %s', $charge->fiat_value, $charge->currency); ?></div>
    </div>

    <div class="payment h-space">
    <div><?php print $h->__('Select bitcoin payment method'); ?>:</div>

    <div>
        <div class="box h-space">
            <div><?php print $h->__('Lightning'); ?></div>
            <div><?php print $h->__('network fee of %s %s', '0.00', 'USD'); ?></div>

            <div class="qr-code">
                <div data-ecl="M" data-address="<?php print $block->escapeHtml($charge->lightning_invoice['payreq']); ?>"></div>
                <div><a href="lightning:<?php print $block->escapeHtml($charge->lightning_invoice['payreq']); ?>"><?php print $h->__('Open in wallet'); ?></a></div>
            </div>
        </div>

        <div class="box h-space">
            <div><?php print $h->__('On Chain'); ?></div>
            <div><?php print $h->__('network fee of %s %s', '0.00', 'USD'); ?></div>

            <div class="qr-code">
                <div data-ecl="M" data-address="<?php print $block->escapeHtml($charge->chain_invoice['address']); ?>"></div>
                <div><a href="lightning:<?php print $block->escapeHtml($charge->chain_invoice['address']); ?>"><?php print $h->__('Open in wallet'); ?></a></div>
            </div>
        </div>
    </div>
    </div>

    <form action="<?php print Mage::getUrl('opennode_bitcoin/payment/cancel'); ?>" method="get">
        <?php echo $this->getBlockHtml('formkey')?>
        <button type="submit">Cancel</button>
    </form>

    <form action="<?php print Mage::getUrl('opennode_bitcoin/payment/success'); ?>" method="get">

        <div id="payment-status-unpaid" class="payment-status payment-status-unpaid">
            <div>Your payment has not been seen in the mempool (if using on-chain payment) or settled in the Ligthning Network.</div>
            <div>If still decide to continue at this point your order will be placed in a Pending Payment status.</div>

            <label for="confirm">I understand. I will continue now instead of waiting for confirmation.</label>
            <input id="confirm" required type="checkbox">

            <button type="submit"><?php print $h->__('I\'ll pay later'); ?></button>
        </div>

        <div id="payment-status-paid" class="payment-status payment-status-unpaid" style="display: none;">
            <button type="submit"><?php print $h->__('Confirm'); ?>/button>
        </div>


        <?php echo $this->getBlockHtml('formkey')?>
    </form>
</div>

<div><?php var_dump($block->getParams());?></div>
<div><?php var_dump($charge);?></div>

<script src="https://cdn.jsdelivr.net/npm/qrcode-svg@1.0.0/dist/qrcode.min.js"></script>
<script>
    document.observe("dom:loaded", function() {
        $$('div[data-address]').forEach(item => {
            if(!item.dataset.address || item.dataset.address.length === 0) {
                item.innerHTML = '<?php print $block->__('Something wrong'); ?>';
                return;
            }

            item.innerHTML = new QRCode({
                content: item.dataset.address,
                padding: 4,
                width: 200,
                height: 200,
                color: '#000000',
                background: '#ffffff',
                ecl: item.dataset.ecl
            }).svg();
        });

        setInterval(function() {
            new Ajax.Request('<?php print $block->escapeHtml($block->getStatusUrl()); ?>', {
                onSuccess: function(response) {

                    console.log(response);

                    if(response.responseJSON.status === 'paid') {
                        $('payment-status-unpaid').style.display = 'none';
                        $('payment-status-paid').style.display = 'none';
                    }

                },
                onFailure: function(response) {
                    console.log(response);
                }
            });
        }, 11000);
    });
</script>

<style>
    .block-opennode .h-space { margin-top: 15px; }
    .block-opennode .payment .box { position: relative; border-left-style: solid; border-left-width: 4px; border-color: #fff; background-color: #fff; -webkit-box-shadow: 0 1px 4px 0 rgba(0,0,0,.08); box-shadow: 0 1px 4px 0 rgba(0,0,0,.08); width: 100%; padding: 1rem; display: -webkit-box; display: -ms-flexbox; display: flex; -webkit-box-align: center; -ms-flex-align: center; align-items: center; border-radius: .375rem; }
    .block-opennode .payment .box:hover { border-color: #4896f0; cursor: pointer; }

    .block-opennode .payment .box .qr-code { display: none; }
    .block-opennode .payment .box:hover .qr-code { display: block; }

    .block-opennode .text-main-dark { color: #1d2229; font-size: 18px; }
    .block-opennode .text-grey-darkest { color: #6f7885; font-size: 14px; }
</style>