<?php
/*
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/** @var OpenNode_Bitcoin_Helper_Data $helper */
$helper = Mage::helper('opennode_bitcoin');

/** @var OpenNode_Bitcoin_Block_Info $block */
$block = $this; ?>

<?php if (is_null($block->getOrder())) : ?>
    <?php print $helper->__('Bitcoin'); ?>
    <?php return; ?>
<?php endif; ?>

<?php $charge = $block->getCharge(); ?>
<?php print $helper->__('Bitcoin'); ?>

<?php if (is_null($charge)) : ?>
    <?php print $helper->__('A valid CHARGE was found for this order. Please contact customer support.'); ?>
    <?php return; ?>
<?php endif; ?>

<ul>
    <li><?php print $helper->__('Status'); ?>: <?php print $block->escapeHtml($charge->getStatusLabel()); ?></li>
    <?php if ($charge->isUnpaid()) : ?>
        <strong><?php print $helper->__('Your order is still unpaid. ') ?></strong>

        <a rel="noopener noreferrer" href="<?php print $block->escapeUrl($block->getInvoiceUrl()) ?>" target="_blank">
            <?php print $helper->__('Pay it now!'); ?>
        </a>
    <?php endif; ?>
</ul>