<?php
/*
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/** @var OpenNode_Bitcoin_Helper_Data $helper */
$helper = Mage::helper('opennode_bitcoin');

/** @var OpenNode_Bitcoin_Block_Info $block */
$block = $this; ?>

<?php if (is_null($block->getOrder())) : ?>
    <?php print $helper->__('Bitcoin'); ?>
    <?php return; ?>
<?php endif; ?>

<?php $charge = $block->getCharge(); ?>
<?php print $helper->__('Bitcoin'); ?>

<table>
    <tbody>
    <tr>
        <td><?php print $helper->__('Status'); ?>:</td>
        <td><?php print $block->escapeHtml($charge->status); ?></td>
    </tr>

    <?php if ($charge->isUnpaid()) : ?>
    <tr>
        <td colspan="2">
            <strong><?php print $helper->__('Your order is still unpaid. ') ?></strong>
        </td>
    </tr>
    <tr>
        <td>
            <a href="<?php print $block->escapeHtml($charge->getLightningInvoice()->formatUri()); ?>">
                <?php print $helper->__('Pay via Lightning Network'); ?>
            </a>
            <a href="<?php print $block->escapeHtml($charge->getChainInvoice()->formatUri($charge->getAmountBtc(), 'Pay')); ?>">
                <?php print $helper->__('Pay On-Chain'); ?>
            </a>
        </td>
    </tr>
    <?php endif; ?>
    </tbody>
</table>