<?php
/*
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/** @var $block OpenNode_Bitcoin_Block_Payment */
$block = $this;

/** @var $h OpenNode_Bitcoin_Helper_Data */
$h = Mage::helper('opennode_bitcoin');

$charge = $block->getCharge(); ?>


<div class="block-opennode" id="block-opennode">
    <input type="hidden" id="__opennodestatusurl__" value="<?php print $block->escapeHtml($block->getStatusUrl()); ?>" />

    <div class="col2-set block-payment-methods">
        <div class="block-title">
            <span><strong><span><?php print $h->__('Select bitcoin payment method'); ?></span></strong></span>
        </div>
        <div class="col-1">
            <?php print $block->getLayout()->createBlock('opennode_bitcoin/method_lightning', 'lightning', [
                'charge' => $charge,
            ])->toHtml(); ?>
        </div>
        <div class="col-2">
            <?php print $block->getLayout()->createBlock('opennode_bitcoin/method_onChain','onchain', [
                'charge' => $charge,
            ])->toHtml(); ?>
        </div>
    </div>

    <div class="col2-set block-actions">
        <div class="col-1"><!-- Just some filler so we can achieve two columns with the default Magento theme! --></div>
        <div class="col-2">
            <div class="box action action-pay">
                <div class="box-content">
                    <form id="payment-status-unpaid" action="<?php print Mage::getUrl('opennode_bitcoin/payment/success'); ?>" method="get">
                        <ul class="form-list">
                            <li style="margin-bottom: 20px;"><?php print $h->__('Your payment has not been seen in the mempool (if using on-chain payment) or settled in the Ligthning Network. If still decide to continue your order will be placed in a <i>Pending Payment</i> status and will be cancelled in 1 hour.'); ?></li>


                            <li class="a-right">
                                <label for="confirm"><?php print $h->__('I understand. I will continue now instead of waiting for confirmation.'); ?></label>
                                <input style="vertical-align: middle;" id="confirm" required class="checkbox" type="checkbox">
                            </li>

                            <li class="a-right">
                                <button class="button" type="submit"><?php print $h->__('I\'ll pay later'); ?></button>
                            </li>
                        </ul>
                    </form>

                    <form id="payment-status-processing" action="<?php print Mage::getUrl('opennode_bitcoin/payment/success'); ?>" method="get" style="display: none;">
                        <ul class="form-list">
                            <li style="margin-bottom: 20px;">
                                <p><?php print $h->__('Your payment was seen in the mempool and is now waiting to be included in a block.'); ?></p>
                            </li>
                            <li class="a-right">
                                <button class="button" type="submit"><?php print $h->__('Continue to order summary'); ?></button>
                            </li>
                        </ul>
                    </form>

                    <form id="payment-status-paid" action="<?php print Mage::getUrl('opennode_bitcoin/payment/success'); ?>" method="get" style="display: none;">
                        <ul  class="form-list">
                            <li>
                                <p><?php print $h->__('Your order was paid successfully.'); ?></p>
                                <p><?php print $h->__('Your should be redirected to the order summary automatically in a few moments.'); ?></p>
                            </li>
                            <li class="a-right">
                                <button class="button" type="submit"><?php print $h->__('Continue to order summary'); ?></button>
                            </li>
                        </ul>

                        <?php echo $this->getBlockHtml('formkey') ?>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="info-set col2-set">
        <div class="col-1">
            <div class="box action-cancel">
                <div class="box-content">
                    <a href="<?php print $block->escapeHtml($block->getCancelUrl()); ?>">
                        <?php print $h->__('Cancel the order and return to %s', $block->getStoreName()); ?>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>



<!--
<div><?php var_dump($block->getParams()); ?></div>
<div><?php var_dump($charge); ?></div>
-->

<style>
    /*.block-opennode .payment-methods {*/
    /*white-space: nowrap;*/
    /*}*/

    .block-opennode .payment-method {
        text-align: center;
        /*display: inline-block;*/
        padding: 20px 0;
        /*white-space: normal;*/
        /*width: 50%;*/
        background-color: #f4f4f4;
        border: 1px solid #cccccc;
    }

    .block-opennode .block-actions .action-pay {
        background-color: #f4f4f4;
        border: 1px solid #cccccc;
        padding: 20px;
        /*width: 50%;*/
    }

    .block-opennode .payment-method .qr-code {
        margin: 10px 0;
        margin: 0 auto;
        width:250px;
    }

    .block-opennode .payment-method .qr-code svg {
        shape-rendering: crispEdges;
    }

    .block-opennode .payment-method .fee {
        font-size: 14px;
    }

    .block-opennode .block-actions {
        clear: both;
    }

    .block-opennode .action-cancel {
        font-size: 11.4px;
    }

    .block-opennode .block-actions .action-pay {
        /*margin-bottom: 30px;*/
    }
</style>