<?php
/*
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/** @var $block OpenNode_Bitcoin_Block_Method_OnChain*/
$block = $this;

/** @var $h OpenNode_Bitcoin_Helper_Data */
$h = Mage::helper('opennode_bitcoin');

$charge = $block->getCharge();
$invoice = $block->getCharge()->getChainInvoice();

$uri = $invoice->formatUri($charge->getAmount(), $block->getStoreName()); ?>

<div class="box payment-method" data-payment-method="onchain">
    <div class="box-title">
        <strong><?php print $h->__('On-Chain'); ?></strong>
    </div>

    <div><?php print $h->__('Standard bitcoin wallet'); ?></div>
    <div><?php print $h->__('%s Satoshis ~ %s BTC', $block->escapeHtml($charge->getAmount()), $block->escapeHtml($charge->getAmountBtc())); ?></div>
    <div><?php print $h->__('%s %s', $charge->getSourceFiatValue(), $charge->getCurrency()); ?></div>

    <?php if($charge->isUnpaid()) : ?>
        <div class="box-content">
            <div class="qr-code" data-qrcode data-address="<?php print $block->escapeHtml($uri); ?>"></div>
            <div data-wallet>
                <a data-wallet-link target="_blank" class="button" href="<?php print $block->escapeHtml($uri); ?>" rel="noopener noreferrer">
                    <?php print $h->__('Open in wallet'); ?>
                </a>
                <button class="button" type="button" data-clipboard-text="<?php print $block->escapeHtml($invoice->getAddress()); ?>">
                    <?php print $h->__('Copy'); ?>
                </button>
            </div>
        </div>
    <?php endif; ?>
</div>